### ISSUE TITLE
The examples fail with "send failed! [...] AddrNotAvailable [...]"

### ISSUE THREAD

**Issue by MindSwipe** [naia-rs/naia#16]
When running the examples with

```
cd demo/server
cargo run --features "use-udp"
```

And

```
cd demo/client
cargo run --bin naia-client-miniquad-example
```

The client panics with the message

> thread 'main' panicked at 'send failed!: Os { code: 10049, kind: AddrNotAvailable, message: "The requested address is not valid in its context." }', C:\Source\naia\client\src\naia_client.rs:456:14

I'm on Windows 10 and it's failing with the exact same panic in my own demo implementation. What's going wrong?

**Comment by MindSwipe** [comment]
Update: I was able to "fix" the error by replacing `127.0.0.1` with my own local IP (i.e `192.168.48.1` in my case) in the client demo `app.rs`, which I find weird.

**Comment by smokku** [comment]
I believe you are experiencing https://github.com/naia-rs/naia-socket/issues/24 issue.

**Comment by MindSwipe** [comment]
Yup, seems like it, thanks for the link
