### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by sayanarijit** [naia-rs/naia#18]
Hi,

Not sure if you are aware, but the documentation page is redirecting to some weird insecure site.

**Comment by naia-rs** [comment]
The docs badge in the README is currently pointing me to https://docs.rs/naia-server/0.5.0/naia_server/ , is that not your experience? Are you clicking on the badge or some other link? What URL is it redirecting to? Thanks for the heads up!

**Comment by sayanarijit** [comment]
Ah really sorry, reported to the wrong repo. I wanted to report to [ws-rs](https://github.com/housleyjk/ws-rs).
