### ISSUE TITLE
bevy client demo cannot be run 

### ISSUE THREAD

**Issue by nyvs** [naia-rs/naia#28]
When I try to run the demo with either nightly or stable, it fails on startup:

`Compiling naia-bevy-client-demo v0.1.0 (/run/media/nyvs/Data/Projects/naia/demos/bevy/client)
    Finished release [optimized] target(s) in 43.69s
     Running `/run/media/nyvs/Data/Projects/naia/target/release/naia-bevy-client-demo`
Jan 08 19:22:53.030  INFO naia_bevy_client_demo::systems::init: Naia Bevy Client Demo started
thread 'main' panicked at 'Requested resource does not exist: alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>', thread '/home/nyvs/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rsthread 'Compute Task Pool (11):Compute Task Pool (15)' panicked at '244' panicked at 'Requested resource does not exist: alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>:Requested resource does not exist: alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>', 17', /home/nyvs/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rs
/home/nyvs/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rs:note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
:244244::1717
`

**Comment by naia-rs** [comment]
Should be fixed in 0.7.3
