### ISSUE TITLE
naia-basic-server-demo cannot be run

### ISSUE THREAD

**Issue by nyvs** [naia-rs/naia#29]
When a client connects, I get this:

`2022-01-08 19:30:34,210 INFO [naia_basic_server_demo::app] Basic Naia Server Demo started
thread 'main' panicked at 'Could not determine the UTC offset on this system. Possible causes are that the time crate does not implement "local_offset_at" on your system, or that you are running in a multi-threaded environment and the time crate is returning "None" from "local_offset_at" to avoid unsafe behaviour. See the time crate's documentation for more information. (https://time-rs.github.io/internal-api/time/index.html#feature-flags): IndeterminateOffset', /home/nyvs/.cargo/registry/src/github.com-1ecc6299db9ec823/simple_logger-1.16.0/src/lib.rs:409:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

Using arch linux,

Thank you for your help

**Comment by loothood** [comment]
The same issue here. MAC OS 11.5.1

**Comment by naia-rs** [comment]
Should be fixed in 0.7.3
