### ISSUE TITLE
Current Games using Naia?

### ISSUE THREAD

**Issue by miketwenty1** [naia-rs/naia#37]
Was looking at this:
https://www.reddit.com/r/rust/comments/hj2eey/naia_a_crossplatform_networking_library_for/
By any chance does this "open-source 100+ player Battle Royale 2D web game" exist yet?

If not, was there any public games I could play around with using naia?

**Comment by naia-rs** [comment]
Sadly it's a no on both questions :/ Maybe I should go back and update that post, but as so often happens, life and unforeseen complications have caused my expectations to remain unmet there. I am still working on it though.

Check out our Discord via the link in the README .. seems like there have been a handful of people working on their own projects using Naia although I haven't seen anyone open-source it yet.

Thanks for the interest though!

**Comment by miketwenty1** [comment]
thanks!
