### ISSUE TITLE
Panic when despawning entities

### ISSUE THREAD

**Issue by oscrim** [naia-rs/naia#40]
When despawning an entity through the naia bevy server and ```EntityMut``` it crashes.  This is due to it trying to get all the entities components in ```EntityManager``` but the entity is not found in the ```WorldRecord``` resulting in it panicking with, ```'entity does not exist!'```.

To reproduce this bug run the naia bevy demo and open up two clients. When both clients have connected, close one of the clients down and then when the connection times out, it will try to remove the entity and eventually crash.

**Comment by cBournhonesque** [comment]
I am getting this issue as well. 
I am trying to despawn an entity, and the server panics with a `entity does not exist` error
